apiVersion: apps/v1
kind: Deployment
metadata:
  name: snrao-demo-devops-app
  labels:    
    app.kubernetes.io/name: demo-devops-app
    app.kubernetes.io/instance: snrao
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    app.name : devops-config-demo-web-app
    env: prod
    version: v1
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-devops-app
      app.kubernetes.io/instance: snrao
  template:
    metadata:
      annotations:
        buildNumber: BUILD_NO_PLACE_HOLDER
      labels:
        app.kubernetes.io/name: demo-devops-app
        app.kubernetes.io/instance: snrao
    spec:
      serviceAccountName: snrao-demo-devops-app
      securityContext:
        {}
      containers:
        - name: demo-devops-app
          securityContext:
            {}
          image: "sannrao/demo-devops-app:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: http
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          # readinessProbe:
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: http
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi